name: Run frontend image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image for the Node.js and Nginx application
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-nginx-app:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-nginx-app:latest

      # Step 6: Run the Docker image to verify it works
      - name: Run the Docker container
        run: |
          docker run -d -p 80:80 --name node-nginx-app ${{ secrets.DOCKER_USERNAME }}/node-nginx-app:latest

      # Step 7: Verify the container is running
      - name: Verify the application
        run: |
          sleep 10 # Allow the container to start
          curl -f http://localhost || (echo "Application did not start" && exit 1)

      # Step 8: Stop and remove the container
      - name: Clean up
        run: |
          docker stop node-nginx-app
          docker rm node-nginx-app

