version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend # Specify the Node.js + Nginx Dockerfile
    ports:
      - "80:80"  # Expose the frontend on port 80

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend # Specify the Spring Boot Dockerfile
    ports:
      - "8080:8080"  # Expose the backend on port 8080

