name: Docker Compose CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the `main` branch

jobs:
  docker:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Build and start services
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # Step 5: Verify services are running (optional)
      - name: Verify Services
        run: |
          docker ps
          curl -f http://localhost:3002  # Check React frontend
          curl -f http://localhost:8081/api/endpoint  # Check Spring Boot backend (replace with actual endpoint)

      # Step 6: Tear down (optional for CI)
      - name: Tear Down Services
        if: always()
        run: docker-compose -f docker-compose.yml down -v

