name: Build and Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the frontend Docker image
      - name: Build Frontend
        run: |
          docker build -t my-frontend:latest -f Dockerfile.frontend .

      # Build the backend Docker image
      - name: Build Backend
        run: |
          docker build -t my-backend:latest -f Dockerfile.backend .

      # Push images to Docker Hub (optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Image
        run: |
          docker tag my-frontend:latest your-dockerhub-username/my-frontend:latest
          docker push your-dockerhub-username/my-frontend:latest

      - name: Push Backend Image
        run: |
          docker tag my-backend:latest your-dockerhub-username/my-backend:latest
          docker push your-dockerhub-username/my-backend:latest

      # Deploy (optional, based on your deployment method)

